# Change these first
owner: Elara6331 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Matrix
    url: https://matrix.arsenm.dev
  - name: Site
    url: https://www.elara.ws
  - name: LURE
    url: https://lure.sh
  - name: Gitea
    url: https://gitea.elara.ws
  - name: Woodpecker CI
    url: https://ci.elara.ws
  - name: SearXNG
    url: https://search.elara.ws
  - name: MinIO (S3)
    url: https://minio.elara.ws
  - name: GZD
    url: https://genzedong.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.elara.ws
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: Status for elara.ws
  introMessage: This is a status page for elara.ws and my other services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/10 * * * *"
